version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.4
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:16.18"
    steps:
      # install node and checkout code
      - node/install:
          node-version: "16.18"
      - checkout
      - aws-cli/setup
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      - run:
          name: Front-End Lint
          command: |
            # npm run frontend:lint
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: API Build
          command: |
            npm run api:build
  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: "16.18"
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: set eb env values
          command: |
            echo "Start set environment"
            eb setenv AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            eb setenv AWS_BUCKET=$AWS_BUCKET
            eb setenv AWS_REGION=$AWS_DEFAULT_REGION
            eb setenv AWS_PROFILE=$AWS_PROFILE
            eb setenv AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            eb setenv JWT_SECRET=$JWT_SECRET
            eb setenv PORT=$PORT
            eb setenv POSTGRES_DB=$POSTGRES_DB
            eb setenv POSTGRES_HOST=$POSTGRES_HOST
            eb setenv POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            eb setenv POSTGRES_PORT=$POSTGRES_PORT
            eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME
            eb setenv URL=$URL
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
            npm run api:deploy
            echo "Finished"

workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
